### ISSUE TITLE
Scoring, iterations and waiting time Munich scenario

### ISSUE THREAD

**Issue by cllorca1** [BauhausLuftfahrt/MATSim-UAM#1]
Running the uam-extension for Munich with the demand generated by the model MITO (msmobility/mito), with the UAMRoutingStrategy.PREDEFINED, which already chooses by itself access/egress stations and modes. 

When I set up the number of MATSim iterations to 50 I found the following results (only UAM demand is simulated): 

Average handling time by iteration (handling time includes a fixe pre-processing, boarding and post-processing plus a demand-dependent component): 
![image](https://user-images.githubusercontent.com/19989489/64783607-88cd9400-d568-11e9-8126-78c34c5d03ef.png)

Scoring: 
![image](https://user-images.githubusercontent.com/19989489/64783647-a00c8180-d568-11e9-87d7-2782cea14c93.png)

As seen, the plan scores get worse after every iteration. The routes get longer as well. The final iteration shows too high waiting times and too long routes. The question is what is MATSim replanning at each iteration. 

Any explanation or quick answer to this? Do I simply need more iterations? And why not use the first iteration directly?

Attached the output config file as well. 
[mito_assignment.output_config.zip](https://github.com/RRothfeld/uam-extension/files/3605417/mito_assignment.output_config.zip)

Thanks!

**Comment by RRothfeld** [comment]
Fixed by changing the networks: UAM links had a freespeed of >99999, while the vehicles travelled with their defined speed <200 which made the router believe there was massive congestion on the flight links and tried to route not the shortest way but the fastest based on the high freespeeds.

the new cachedintermodalrouter pre-calculates all routes so this is not an issue right now, but might become one once a new router does calculate the routes ad-hoc every time.
