### ISSUE TITLE
UAMLinkSpeedCalculator unused since update to MATSim 12

### ISSUE THREAD

**Issue by RRothfeld** [BauhausLuftfahrt/MATSim-UAM#74]
It seems that UAM travel speeds are now based solely on link's freespeeds, see: https://github.com/BauhausLuftfahrt/MATSim-UAM/blob/b2acd6828c1ecd440dd3e0778302a783e460b000/src/main/java/net/bhl/matsim/uam/run/UAMModule.java#L91

https://github.com/BauhausLuftfahrt/MATSim-UAM/blob/master/src/main/java/net/bhl/matsim/uam/qsim/UAMSpeedModule.java and https://github.com/BauhausLuftfahrt/MATSim-UAM/blob/master/src/main/java/net/bhl/matsim/uam/qsim/UAMLinkSpeedCalculator.java are unsused during simulation, leading to UAM speeds being equal link freespeed.

Would you propose creating a new TravelTime implementation for UAM that does the job or do you have other ideas?

**Comment by sebhoerl** [comment]
I just had a quick look. Actually, are you sure that this was working properly lately? Looking at the [history of `UAMSpeedModule`](https://github.com/BauhausLuftfahrt/MATSim-UAM/commits/master/src/main/java/net/bhl/matsim/uam/qsim/UAMSpeedModule.java), the provider for `QNetworkFactory` was commented out already on *19 November 2019*. So since then `UAMLinkSpeedCalculator` was not used anywhere.

Two options:
- Either the speed is encoded in the network (which, I think, is probably the case right now?). However, then it is certainly not vehicle-dependent.
- Put back in `UAMLinkSpeedCalculator`, then it can be made vehicle-depedent again (which, I suppose, was the major functionality of the calculator).

**Comment by RRothfeld** [comment]
Sorry, Sebastian, you are right course. It was undetected from previous changes. not from MATSim v12; and yes, the idea is that it's vehicle dependent.

I'll have a look into reactivation but am struggling a bit, see branch https://github.com/BauhausLuftfahrt/MATSim-UAM/tree/issue-74
